---
- name: 'Import tasks'
  include_tasks: "{{ tasks_file }}.yml"
  loop: "{{ global_common_settings | default([]) }}"
  loop_control:
    loop_var: 'tasks_file'

- name: 'Prepare host specific task list'
  merge_vars:
    suffix_to_merge: '_common_settings__to_merge'
    merged_var_name: 'host_tasks'
    expected_type: 'list'

- name: 'Import host-specific common tasks'
  include_tasks: "{{ host_tasks_file }}.yml"
  loop: "{{ host_tasks }}"
  loop_control:
    loop_var: 'host_tasks_file'
