---
- name: 'Set root password'
  # Set a root password on all non-LXC systems
  # Uses a deterministic salt to prevent the task from returning changed all the time
  user:
    name: 'root'
    comment: "root at {{ ansible_facts['hostname'] }}"
    password: >-
      {% if ansible_facts['virtualization_type'] == 'lxc'
         and ansible_facts['virtualization_role'] == 'guest' %}
      !{%- else -%}
      {{ root_password | string | password_hash('sha512', (root_salt + ansible_facts['fqdn'] | string ) | hash('sha512') | truncate(16, true), rounds=root_hash_rounds) }}
      {%- endif -%}

- name: 'Ensure sudo installed'
  package:
    name: 'sudo'
    state: 'present'
